# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Xilinx Alveo clock devices
#

xrt-clock-objs			:= clock.o
obj-$(CONFIG_XRT_CLK_WIZ)	+= xrt-clock.o

xrt-clkfreq-objs		:= clkfreq.o
obj-$(CONFIG_XRT_CLK_FREQ)	+= xrt-clkfreq.o

xrt-ucs-objs			:= ucs.o
obj-$(CONFIG_XRT_CLK_UCS)	+= xrt-ucs.o
