/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Copyright (C) 2023, Advanced Micro Devices, Inc.
 */
#ifndef __DMA_MQDMA_HW_H
#define __DMA_MQDMA_HW_H

#define QDMA_GLBL2_CHANNEL_FUNC_RET	0x12c
#define QDMA_GLBL2_FUNC_ID_MASK		GENMASK(7, 0)

#define QDMA_GLBL2_MISC_CAP		0x134
#define QDMA_GLBL2_DEV_TYPE_MASK	GENMASK(31, 28)
#define QDMA_DEV_CPM5			0x2

#define QDMA_MM_CONTROL_RUN		0x1
#define QDMA_MM_CONTROL_STEP		0x100

#define QDMA_IND_CTXT_DATA_BASE		0x804
#define QDMA_IND_CTXT_MASK_BASE		0x824
#define QDMA_IND_CTXT_CMD		0x844

#define QDMA_REG_GLBL_RNG_SZ_BASE	0x204

#define QDMA_OFFSET_C2H_MM_CONTROL	0x1004
#define QDMA_OFFSET_H2C_MM_CONTROL	0x1204

/*
 * Q Context programming (indirect)
 */
enum ind_ctxt_cmd_op {
	QDMA_CTXT_CMD_CLR,
	QDMA_CTXT_CMD_WR,
	QDMA_CTXT_CMD_RD,
	QDMA_CTXT_CMD_INV
};

enum ind_ctxt_cmd_sel {
	QDMA_CTXT_SEL_SW_C2H,
	QDMA_CTXT_SEL_SW_H2C,
	QDMA_CTXT_SEL_HW_C2H,
	QDMA_CTXT_SEL_HW_H2C,
	QDMA_CTXT_SEL_CR_C2H,
	QDMA_CTXT_SEL_CR_H2C,
	QDMA_CTXT_SEL_CMPT,
	QDMA_CTXT_SEL_PFTCH,
	QDMA_CTXT_SEL_INT_COAL,
	QDMA_CTXT_SEL_PASID_RAM_LOW,
	QDMA_CTXT_SEL_PASID_RAM_HIGH,
	QDMA_CTXT_SEL_TIMER,
	QDMA_CTXT_SEL_FMAP,
};

#define QDMA_CTXT_CMD_BUSY		BIT(0)
#define QDMA_CTXT_CMD_SEL		GENMASK(4, 1)
#define QDMA_CTXT_CMD_OP		GENMASK(6, 5)
#define QDMA_CTXT_CMD_ID		GENMASK(19, 7)

#define QDMA_CTX_CMD(sel, op, id)				\
	(FIELD_PREP(QDMA_CTXT_CMD_SEL, sel) |			\
	 FIELD_PREP(QDMA_CTXT_CMD_ID, id) |			\
	 FIELD_PREP(QDMA_CTXT_CMD_OP, op))

#define QDMA_IND_CTXT_POLL_INTERVAL	10		/* us */
#define QDMA_IND_CTXT_POLL_COUNT	50000

#define CTXT_REG_COUNT			8
struct qdma_ind_ctxt {
	u32	data[CTXT_REG_COUNT];
	u32	mask[CTXT_REG_COUNT];
	u32	cmd;
};

struct qdma_device;
int qdma_cpm5_init(struct qdma_device *qdev);

#endif
